Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,30 +1,34 @@
 name: Build with Maven and generate reports
 
-on: [push,pull_request]
+on: [push, pull_request]
 
 jobs:
-
   build:
 
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
+
     - name: Set up JDK 8
       uses: actions/setup-java@v3
       with:
         java-version: '8'
         distribution: 'temurin'
         cache: maven
-    
+
     - name: Build with Maven
-      run: | 
-        mvn -B package --file pom.xml || echo "BUILD FAILED" > build_failed.flag 
+      run: |
+        mvn -B clean package --file pom.xml || echo "BUILD FAILED" > build_failed.flag
+
     - name: Upload coverage to Coveralls
       if: always()
       env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: mvn coveralls:report
+
+    - name: Generate Checkstyle report
+      run: mvn checkstyle:checkstyle
 
     - name: Create site
       if: always()
@@ -37,6 +41,13 @@ jobs:
           echo "<html><body><h1>Report Index</h1></body></html>" > target/site/index.html
         fi
 
+    - name: Upload Checkstyle report as artifact
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: checkstyle-report
+        path: target/checkstyle-*.xml
+
     - name: Deploy report to GitHub Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v4
@@ -45,10 +56,7 @@ jobs:
         publish_dir: ./target/site
 
     - name: Fail job if build failed
-    #Qui infatti, si controlla se è stata generata la flag di fail. Se si restituisce l'esito "Build failed", altrimenti siamo arrivati alla fine grazie ai vari if always()
-      if: always()
+      if: failure()
       run: |
-        if [ -f build_failed.flag ]; then 
-          echo "Build failed"
-          exit 1
-        fi
+        echo "Build failed"
+        exit 1
